### ISSUE TITLE
Generate the trajectory figure of the top-down view

### ISSUE THREAD

**Issue by mengdi-li** [barmayo/spatial_attention#1]
Hi, I am wondering if we can generate the top-down trajectory figure (Figure1, (a) Paths in your paper) by using the code of this repository? If not, could you please elaborate on how did you get this kind of visualization figure? Thanks!

**Comment by barmayo** [comment]
Hi,
Unfortunately the code the create the trajectories is not in the repository.
But, If I remember correctly, the procedure is pretty simple:
 1. You can use the code here for top view maps: https://github.com/allenai/ai2thor/issues/124
 2. The metadata contains agent's location coordinates. Just use them to draw the path.

Note: I know AI2-THOR frequently update their code, so some commands might change in newer versions. I would also look into the tutorial in AI2-THOR's website.

**Comment by mengdi-li** [comment]
Thanks very much! I will check it out.

**Comment by LeeGe91** [comment]
Could you please give me the ore-trained models?thanks
