### ISSUE TITLE
Generate the attention figure

### ISSUE THREAD

**Issue by Ameelis** [barmayo/spatial_attention#2]
Hi, do you provide the code to generate your attention figure?

**Comment by barmayo** [comment]
Hi,

Unfortunately, I don't have a code that generates the attention figures. But the procedure should be simple enough:
You will find the attention maps calculated in model/basemode.py (lines 71-74). For a good visualization, just resize the maps and print over the original input image with some alpha value (transparency) using cv2 or matplotlib.

Hope this helps :)

**Comment by Ameelis** [comment]
Hi,

I am still lost. Could you tell me what exact function you use in matplotlib? Thank you.

**Comment by barmayo** [comment]
Hi,

I don't recall the exact functions I used but running a short google search:
- Plotting heatmaps: https://matplotlib.org/stable/gallery/images_contours_and_fields/pcolor_demo.html
- Plotting transparent images: https://matplotlib.org/stable/gallery/images_contours_and_fields/image_transparency_blend.html
- Image resize: https://www.tutorialkart.com/opencv/python/opencv-python-resize-image/

Good luck!
