### ISSUE TITLE
Attention Figure

### ISSUE THREAD

**Issue by Ameelis** [barmayo/spatial_attention#3]
Hi,

In Figure 3 of your paper, the size of the Fused map is: torch.Size([49]).

The original image input is: (300, 300, 3).

I want to know how do you manage the size of these two inputs (original image and fused map) to obtain your Attended embedding? Could you help me in details, like how and what you do to resize the map?

Last time, you give me the link: 
- Plotting transparent images: 
- https://matplotlib.org/stable/gallery/images_contours_and_fields/image_transparency_blend.html

But it is for 2D image, I am still confused.

Thank you. Looking forward to your reply!

**Comment by barmayo** [comment]
Hi,

I'll explain the calculation, but I would advice going back and read the paper for more information:

1. The ResNet-18 extract feature matrix sized 7x7x512. Practically, its divides the image to 7x7 equal section for each a feature vector of 512 describing the information found in that section of the image. We reshape it to 512x49 (line 51 in basemode.py)
2. We re-embed each feature vector to 64 for the image sections, memory, action and target string (lines 56-69 in basemodel.py). This outputs 64x49 matrix for the image and 64x1 for the other features.
3. We multiply each feature vector: (1x64)X(64x49) = 1x49. This is heat map - 49 attention value for each of the 49 section of the image (lines 76-78 in basemodel.py).

To visualize the attention map you should reshape it back to 7x7, resize it to original input image size (300x300) and plot it over that image.

Hops this makes things clearer,
Bar

**Comment by Ameelis** [comment]
Hi,

Thank you for your very detailed reply about how do you obtain the heat map.

However, my previous question is mainly about visualizing the attention map. I am sorry that I do not make my question clear enough.

I would like to know how do you reshape the heat map to 7x7? How do you then resize it to 300x300? And how do you plot the attention image because the original image is 300x300x3?

Do you have special ways to finish these processes?

Thanks again for your very patient reply, I really greatly appreciate it!

**Comment by barmayo** [comment]
Hi,

There is probably more than one way to do those things, but I would advice the following tutorial:
- For reshaping matrix: https://www.tensorflow.org/api_docs/python/tf/reshape
- For resizing images*: https://www.tutorialkart.com/opencv/python/opencv-python-resize-image/
- For overlying one image over the other: https://stackoverflow.com/questions/40895785/using-opencv-to-overlay-transparent-image-onto-another-image/46198932

*Note:
-  In order to transform a 300x300x1, a single channel image, to a 300x300x3, a three channels image, you can just use something like "cv2.merge((image, image, image))".  

Good luck,
Bar

**Comment by Ameelis** [comment]
Hi,

Thank you for your super detailed information.

Here shows the steps I did to generate the attention map you told me, but the final fused map is dark or grey. Could you help to check where is not correct:

Suppose the original input image is: [https://github.com/Ameelis/attention-map/blob/main/color_img.jpg](https://github.com/Ameelis/attention-map/blob/main/color_img.jpg)

**_(1) reshape the Fused map (denote by poten) to 7x7, whose original size is 49._**

poten_1 = np.array([0.0195, 0.0204, 0.0178, 0.0223, 0.0188, 0.0187, 0.0190, 0.0187, 0.0194,
                      0.0161, 0.0145, 0.0168, 0.0135, 0.0147, 0.0241, 0.0178, 0.0149, 0.0157,
                      0.0150, 0.0184, 0.0173, 0.0198, 0.0181, 0.0234, 0.0242, 0.0203, 0.0166,
                      0.0244, 0.0340, 0.0347, 0.0246, 0.0174, 0.0162, 0.0185, 0.0239, 0.0260,
                      0.0225, 0.0256, 0.0220, 0.0224, 0.0196, 0.0246, 0.0307, 0.0257, 0.0162,
                      0.0170, 0.0149, 0.0196, 0.0237])
poten_1 = poten_1.reshape(7, 7)

poten_1 is obtained using your code. I also randomly generate a Fused map:

poten_2 = np.random.randint(256, size=(7, 7), dtype='uint8')

I show poten_1 and poten_2 as follows:

code:
plt.imshow(poten, cmap="viridis")
plt.show()

poten_1: [https://github.com/Ameelis/attention-map/blob/main/attention_img_2022_02_16_11_41_05.png](https://github.com/Ameelis/attention-map/blob/main/attention_img_2022_02_16_11_41_05.png)

poten_2: [https://github.com/Ameelis/attention-map/blob/main/attention_img_2022_02_16_12_38_06.png](https://github.com/Ameelis/attention-map/blob/main/attention_img_2022_02_16_12_38_06.png)


**_(2) resize the Fused map to 300x300._**

new_poten_1 = cv2.resize(poten_1, (300, 300), interpolation=cv2.INTER_LINEAR)
new_poten_2 = cv2.resize(poten_2, (300, 300), interpolation=cv2.INTER_LINEAR)

code:
plt.imshow(new_poten, cmap="viridis")
plt.show()

new_poten_1: [https://github.com/Ameelis/attention-map/blob/main/resize_attention_300_2022_02_16_11_56_09.png](https://github.com/Ameelis/attention-map/blob/main/resize_attention_300_2022_02_16_11_56_09.png)

new_poten_2: [https://github.com/Ameelis/attention-map/blob/main/resize_attention_300_2022_02_16_12_38_06.png](https://github.com/Ameelis/attention-map/blob/main/resize_attention_300_2022_02_16_12_38_06.png)

**_(3) change channels of Fused map to 3, that is 300x300x3._**

attention_1 = cv2.merge((new_poten_1, new_poten_1, new_poten_1))
attention_2 = cv2.merge((new_poten_2, new_poten_2, new_poten_2))

code:
plt.imshow(attention, cmap="viridis")
plt.show()

attention1: [https://github.com/Ameelis/attention-map/blob/main/final_attention_2022_02_16_12_07_44.png](https://github.com/Ameelis/attention-map/blob/main/final_attention_2022_02_16_12_07_44.png)

attention2: [https://github.com/Ameelis/attention-map/blob/main/final_attention_2022_02_16_12_38_06.png](https://github.com/Ameelis/attention-map/blob/main/final_attention_2022_02_16_12_38_06.png)

**_(4) overlying the Fused map over the original input image:_**

background = cv2.imread('color_img.jpg')
overlay = attention
added_image = cv2.addWeighted(background, 0.9, overlay, 0.3, 0)

- Because the Fused map is dark or grey, so I do not display the final attended embedding.

Thank you very much for your help!!!

**Comment by barmayo** [comment]
Hi,

I'm not sure exactly what is the problem. my guess:
-  Matplotlib might tries to plot image with values range of [0,255] instead of [0,1]. To check this just multiply the merged image by 255.
- Maybe its something relating to the type of the data (this happened to me a lot with cv2). If you are using [0,255] range, change the data type to 'uint8'.

Good luck!

**Comment by Ameelis** [comment]
Hi,

Thank you very much for your reply.

I can use the following equation to make the values range from [0,1] to [0,255]:

poten_1 = ((poten_1 - poten_1.min()) * (1 / (poten_1.max() - poten_1.min()) * 255)).astype('uint8')

The poten_1 is:

[[ 72  82  51 105  63  62  66]
 [ 62  70  31  12  39   0  14]
 [127  51  16  26  18  58  45]
 [ 75  55 119 128  81  37 131]
 [246 255 133  46  32  60 125]
 [150 108 145 102 107  73 133]
 [206 146  32  42  16  73 122]]

Then, resize to 300:

new_poten_1 = cv2.resize(poten_1, (300, 300), interpolation=cv2.INTER_LINEAR)

The image after transform is: [https://github.com/Ameelis/attention-map/blob/main/resize_attention_300_2022_02_16_11_56_09.png](https://github.com/Ameelis/attention-map/blob/main/resize_attention_300_2022_02_16_11_56_09.png)

However, after I use:  

attention = cv2.merge([new_poten_1, new_poten_1, new_poten_1])

It always shows a grey image:

[https://github.com/Ameelis/attention-map/blob/main/Figure_1.png](https://github.com/Ameelis/attention-map/blob/main/Figure_1.png)

So I can not obtain a colorful attended embedding shown in your paper ~

**Comment by snow2white** [comment]
hi

When I use opencv there is also a problem with the gray image, but I don't have this problem using matplotlib. Although the drawing is different from the paper, I think it should be the parameter problem of the function.
