### ISSUE TITLE
test or val?

### ISSUE THREAD

**Issue by snow2white** [barmayo/spatial_attention#6]
Hi,
I would like to ask if test_val_split is randomly generated

**Comment by barmayo** [comment]
Hi,

I used the same settings as the paper "Learning to Learn How to Learn: Self-Adaptive Visual Navigation using Meta-Learning"

You can find the paper here: https://openaccess.thecvf.com/content_CVPR_2019/papers/Wortsman_Learning_to_Learn_How_to_Learn_Self-Adaptive_Visual_Navigation_Using_CVPR_2019_paper.pdf

And the code here : https://github.com/allenai/savn/

**Comment by snow2white** [comment]
Great, thanks!

**Comment by LeeGe91** [comment]
Could you please give me the ore-trained models?thanks
